In [1]:
import tensorflow as tf
from tensorflow.keras.layers import LSTM
import numpy as np

# LSTM层的参数 - return_sequences和return_state

这两个参数都会影响LSTM层的输出。返回的内容不同。  
![](https://windmissing.github.io/Bible-DeepLearning/assets/images/Chapter10/8.png)  
`return_sequences`是控制如何返回图中的output,`return_state`是控制如何返回图中的state。  

## return_sequences = False, return_state = False

例：  
输入数据为：`X.shape = (1,2,1)`,即1个样本，2个时间步，1个特征  
输出数据为：`shape=(1, 1)`，即1个样本，在LSTM最后一个时间步的output，output向量是一维的

In [2]:
X = tf.constant([[[1],[2]]],dtype=tf.float32)
layer = LSTM(1)
layer(X)  

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.103333]], dtype=float32)>

## return_sequences = True, return_state = False

例：  
输入数据为：X.shape = (1,2,1),即1个样本，2个时间步，1个特征  
输出数据为：shape=(1, 2, 1)，即1个样本，2个时间步，每个时间步输出一个output，output向量是一维的

In [3]:
X = tf.constant([[[1],[2]]],dtype=tf.float32)
layer = LSTM(1,return_sequences = True)
layer(X)  

<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[0.08441012],
        [0.10217844]]], dtype=float32)>

## return_sequences = False, return_state = True

例：  
输入数据为：X.shape = (1,2,1),即1个样本，2个时间步，1个特征  
输出数据有三个，依次为：  
输出1：shape=(1, 1)，1个样本，在LSTM最后一个时间步的output，output向量是一维的  
输出2：shape=(1, 1)，1个样本，在LSTM最后一个时间步的output，output向量是一维的  
输出3：shape=(1, 1)，1个样本，在LSTM最后一个时间步的state，state向量是一维的

In [4]:
X = tf.constant([[[1],[2]]],dtype=tf.float32)
layer = LSTM(1,return_state = True)
layer(X)  

[<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.07225075]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.07225075]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.16183122]], dtype=float32)>]

## return_sequences = True, return_state = True

例：  
输入数据为：X.shape = (1,2,1),即1个样本，2个时间步，1个特征  
输出数据有三个，依次为：  
输出1：shape=(1, 2, 1)，即1个样本，2个时间步，每个时间步输出一个output，output向量是一维的   
输出2：shape=(1, 1)，即1个样本，在LSTM最后一个时间步的output，output向量是一维的  
输出3：shape=(1, 1)，即1个样本，在LSTM最后一个时间步的state，state向量是一维的

In [5]:
X = tf.constant([[[1],[2]]],dtype=tf.float32)
layer = LSTM(1, return_sequences = True, return_state = True)
layer(X)  

[<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
 array([[[0.12106458],
         [0.21484499]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.21484499]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.43435505]], dtype=float32)>]