In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Softmax
import numpy as np

# Softmax层

[softmax](https://windmissing.github.io/Bible-DeepLearning/Chapter6/2Gradient/2OutputUnit/3Softmax.html)

In [10]:
X = tf.constant([1,2,3,4,5],dtype=tf.float32)
layer = Softmax()
layer(X)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.01165623, 0.03168492, 0.08612854, 0.23412165, 0.6364086 ],
      dtype=float32)>

# 对二维数据的某一个维度做softmax

输入二维数据为：  
1 2 3  
1 1 1  
默认对最低维度做softmax,即分别对[1 2 3]和[1 1 1]做softmax

In [16]:
X = tf.constant([[1,2,3],[1,1,1]],dtype=tf.float32)
layer = Softmax()
layer(X)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.33333334, 0.33333334, 0.33333334]], dtype=float32)>

也可以指定对哪个维度做softmax,例如  
输入二维数据  
1 2 3  
1 1 1  
指定axis=0，分别对[1 1]、[2 1]、[3 1]做softmax

In [17]:
X = tf.constant([[1,2,3],[1,1,1]],dtype=tf.float32)
layer = Softmax(axis=0)
layer(X)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.5       , 0.7310586 , 0.880797  ],
       [0.5       , 0.26894143, 0.11920291]], dtype=float32)>

以上方法对高维数据同样适用