# linalg

In [2]:
import numpy as np
from numpy import linalg as la

# 奇异值分解

In [5]:
U,Sigma,VT=np.linalg.svd([[1, 1],[7, 7]])
U

array([[-0.14142136, -0.98994949],
       [-0.98994949,  0.14142136]])

In [6]:
Sigma

array([1.00000000e+01, 2.82797782e-16])

In [7]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

# 特征值分解

In [10]:
eigVals, eigVecs = np.linalg.eig([[1, 1],[6, 7]])
eigVals

array([0.12701665, 7.87298335])

In [11]:
eigVecs  # 一个特征值对应一个列向量

array([[-0.75332908, -0.1439812 ],
       [ 0.65764374, -0.98958042]])

# 求欧式距离

In [13]:
A=np.array([1,2])
B=np.array([3,4])
la.norm(A - B)

2.8284271247461903