# matrix

# 创建矩阵

In [17]:
# 二维数据创建矩阵
import numpy as np
np.mat([[1,2,3],[2,3,4]])

matrix([[1, 2, 3],
        [2, 3, 4]])

In [18]:
# 一维数据创建矩阵, 得到的是1*n的二维矩阵
np.mat([1,2,3])

matrix([[1, 2, 3]])

# 矩阵求逆

In [2]:
import numpy as np
M = np.mat([[1,2,3],[2,3,4]])
M.T

matrix([[1, 2],
        [2, 3],
        [3, 4]])

In [4]:
import numpy as np
M = np.mat([[1,2,3],[2,3,4]])
M.transpose()

matrix([[1, 2],
        [2, 3],
        [3, 4]])

# 矩阵乘法

In [5]:
A = np.mat([[1,1],[1,1]])
B = np.mat([[2,2],[2,2]])
A * B   # 点乘，这是matrix与array的区别

matrix([[4, 4],
        [4, 4]])

In [6]:
A.dot(B)   # 点乘

matrix([[4, 4],
        [4, 4]])

In [7]:
np.multiply(A, B)   # 相乘

matrix([[2, 2],
        [2, 2]])

# 矩阵和向量的乘法

In [10]:
A = np.matrix([[1,1,1],[2,2,2]])
b = np.ones(3)
A.dot(b)

matrix([[3., 6.]])

In [13]:
# 虽然对matrix来说，dot和*都代表点乘，但矩阵和向量相乘时结果不一样
A * b

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [14]:
# 即使b转置成向量也不行
A * b.T

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [16]:
# 只能两个矩阵相乘，向量要转成n*1的矩阵
c = np.ones((3,1))
A * c

matrix([[3.],
        [6.]])

# 两个向量相乘

In [5]:
import numpy as np
a = np.mat(np.ones(3))   # 1*3的矩阵
b = np.mat(np.ones(3)).T # 3*1的矩阵
c = a * b
c # 理论上应该得到一个数字，实际上得到的是1*1的矩阵

matrix([[3.]])

In [7]:
c.getA()[0][0] # 1*1的矩阵转成数字的方法一

3.0

In [8]:
float(c)       # 1*1的矩阵转成数字的方法二

3.0

# matrix 转array

In [3]:
import numpy as np
X = np.matrix([[1,1,1],[2,2,2]])
X.getA()

array([[1, 1, 1],
       [2, 2, 2]])

In [4]:
X = np.matrix([[1],[2],[3]])
X.getA()

array([[1],
       [2],
       [3]])

In [5]:
X = np.matrix([[1,2,3]])
X.getA()

array([[1, 2, 3]])