# 针对一个矩阵的操作

In [1]:
import numpy as np   # 调用numpy函数时显示地使用"np."来调用，以区分这个函数是否属于numpy

# 创建矩阵

In [2]:
# 创建二维数组
np.array([[1,1,1],[2,2,2]])

array([[1, 1, 1],
       [2, 2, 2]])

In [3]:
# 创建一维数组
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# 创建全0的矩阵
np.zeros((3, 4))   # 注意这里有两层小括号

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 获取矩阵在大小

## 二维数组有几行

In [5]:
A = np.array([[1,1,1],[2,2,2]])
A.shape[0]

2

In [6]:
import numpy as np
A = np.array([[1,1,1],[2,2,2]])
len(A)

2

## 二维数组有几列

In [7]:
A = np.array([[1,1,1],[2,2,2]])
A.shape[1]

3

In [8]:
A = np.array([[1,1,1],[2,2,2]])
len(A[0])

3

## 一维数组有几个元素

In [9]:
a = np.array([1,2,3])
a.shape[0]

3

In [10]:
a = np.array([1,2,3])
len(a)

3

# 取矩阵的一部分

In [11]:
# 取矩阵第一列
A = np.array([[1,1,1],[2,2,2]])
A[:,1]

array([1, 2])

In [12]:
# 取矩阵最后一列
A = np.array([[1,2,3],[4,5,6]])
A[:,-1]

array([3, 6])

In [5]:
# 取满足要求的某几个样本
import numpy as np
A = np.array([[1,1,1],
             [2,2,2],
             [3,3,3],
             [4,4,4]])
A[A[:,0]%2==0]

array([[2, 2, 2],
       [4, 4, 4]])

In [8]:
# 去掉样本的某一个特征
A = np.array([[1,2,3,4],
             [2,3,4,5],
             [3,4,5,6]])
np.hstack([A[:,:2],A[:,3:]])

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]])

# 取矩阵中的非零元素的索引

In [2]:
# list
import numpy as np
a = [1,0,2,0,3]
np.nonzero(a)

(array([0, 2, 4], dtype=int64),)

In [5]:
# 一维向量
import numpy as np
a = np.array([1,0,2,0,3])
np.nonzero(a)

(array([0, 2, 4], dtype=int64),)

In [4]:
# 二维向量某一列的非零元素
A = np.array([[1,1],
    [2,0],
    [3,1],
    [4,0]])
np.nonzero(A[:,1])

(array([0, 2], dtype=int64),)

In [8]:
# 二维数组某一列的非零元素
B = np.mat([[1,1],
    [2,0],
    [3,1],
    [4,0]])
np.nonzero(B[:,1])

(array([0, 2], dtype=int64), array([0, 0], dtype=int64))

In [16]:
# 只有一列的二维数组
C = np.array([[1],
    [0],
    [1],
    [0]])
np.nonzero(C)

(array([0, 2], dtype=int64), array([0, 0], dtype=int64))

# 计算矩阵的秩

In [2]:
import numpy as np
A = np.array([[1,2],[3,4]])
np.linalg.det(A)

-2.0000000000000004

# 矩阵的扩展

In [13]:
A = np.array([[1,2,3],
              [4,5,6]])
np.tile(A, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# 对数组的排序并返回结果索引

In [14]:
a = np.array([1,3,5,7,2,4,6,8])
a.argsort()  # 默认从小到大

array([0, 4, 1, 5, 2, 6, 3, 7], dtype=int64)

# 二维数组元素求和

In [15]:
A = np.array([[1,2,3],
              [4,5,6]])

In [16]:
A.sum(axis=1)   # 按行求和，方法一

array([ 6, 15])

In [17]:
np.sum(A, axis=1)    # 按行求和，方法二

array([ 6, 15])

In [18]:
A.sum(axis=0)   # 按列求和，方法一
# NOTE: 虽然是按列计算，但是得到的是一个行向量

array([5, 7, 9])

In [19]:
np.sum(A, axis=0)    # 按列求和，方法二

array([5, 7, 9])

除了求和以外，还有其它操作：  
求行最大值：A.max(axis=1) 或 np.max(A, axis=1)  
求行最小值：A.min(axis=1) 或 np.min(A, axis=1)  

# 标准化

In [20]:
dataSet = np.array([[1,2,3],
                   [2,4,6],
                   [3,6,9],
                   [4,8,9]])

def autoNorm(dataSet):
    max = np.max(dataSet, axis=0)
    min = np.min(dataSet, axis=0)
    return ((dataSet -min) / (max-min))

autoNorm(dataSet)

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.5       ],
       [0.66666667, 0.66666667, 1.        ],
       [1.        , 1.        , 1.        ]])

# 计算方差

In [4]:
# 一维数组的方差
import numpy as np
a = np.array([1,2,3])
b = np.array([1,1,1])
print(a.var(),b.var())

0.6666666666666666 0.0


In [5]:
# 二维数组的方差
import numpy as np
dataSet = np.array([[1,2,3],
                   [2,4,6],
                   [3,6,9],
                   [4,8,9]])
dataSet.var() # 默认是所有数字的方差，不是协方差

7.1875

# 计算平均值

In [12]:
# 一维数组的平均值
import numpy as np
a = np.array([1,2,3])
print(a.mean())
print (a.mean(axis=0)) # 两种写法

2.0
2.0


In [7]:
# 二维数组的平均值
import numpy as np
dataSet = np.array([[1,2,3],
                   [2,4,6],
                   [3,6,9],
                   [4,8,9]])
dataSet.var()  # 默认是求所有数据的平均值

4.75

In [8]:
dataSet.mean(axis =0)  # axis=0，求得每一列的平均值，结果=列数

array([2.5 , 5.  , 6.75])

In [10]:
dataSet.mean(axis=1) # axis=1，求得每一行的平均值，结果=行数，但仍是行向量

array([2., 4., 6., 7.])

In [17]:
import numpy as np
A = np.array([4,5,1,2,3])
A.argmin()

2