# 两个同维度的对象之间的操作

In [1]:
import numpy as np

# 两个向量拼接

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [3]:
np.hstack([a,b])    # 指定横向拼接，拼接后还是向量

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.vstack([a,b])    # 指定纵向拼接，拼接后是数组

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
np.stack([a,b])    # 如果没有指定，默认纵向拼接，即拼接成数组

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 两个矩阵拼接

In [6]:
A = np.array([[1,2,3,4],
            [5,6,7,8]])
B = np.array([[2,3,4,5],
             [6,7,8,9]])

In [7]:
np.hstack([A, B])       # 指定横向拼接，2个m*n拼接成m*2n

array([[1, 2, 3, 4, 2, 3, 4, 5],
       [5, 6, 7, 8, 6, 7, 8, 9]])

In [8]:
np.vstack([A, B])       # 指定纵向拼接，2个m*n拼接成2m*n

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [9]:
np.stack([A, B])        # 如果没有指定，会拼接成更高维度的矩阵，2个m*n拼接成2*m*n

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[2, 3, 4, 5],
        [6, 7, 8, 9]]])

# 两个向量的相关性

In [4]:
import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([2,3,4,5,7])
np.corrcoef(A, B)

array([[1.        , 0.98639392],
       [0.98639392, 1.        ]])