In [1]:
import numpy as np   # 调用numpy函数时显示地使用"np."来调用，以区分这个函数是否属于numpy

# 创建矩阵

In [8]:
# 创建二维数组
np.array([[1,1,1],[2,2,2]])

array([[1, 1, 1],
       [2, 2, 2]])

In [9]:
# 创建一维数组
np.array([1,2,3])

array([1, 2, 3])

# 获取矩阵在大小

In [11]:
# 二维数组有几行
A = np.array([[1,1,1],[2,2,2]])
A.shape[0]

2

In [13]:
# 二维数组有几列
A = np.array([[1,1,1],[2,2,2]])
A.shape[1]

3

In [15]:
# 一维数组有几个元素
a = np.array([1,2,3])
a.shape[0]

3

# 矩阵（二维数组）与向量（一维数组）的加减

In [17]:
A = np.array([[1,1,1],[2,2,2]])
b = [1,2,3]
A - b
# A的列数必须 = b的列数，ret_i_j = A_i_j - b_j

array([[ 0, -1, -2],
       [ 1,  0, -1]])

# 矩阵的扩展

In [20]:
A = np.array([[1,2,3],
              [4,5,6]])
np.tile(A, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# 对数组的排序并返回结果索引

In [22]:
a = np.array([1,3,5,7,2,4,6,8])
a.argsort()  # 默认从小到大

array([0, 4, 1, 5, 2, 6, 3, 7], dtype=int64)

# 二维数组元素求和

In [23]:
A = np.array([[1,2,3],
              [4,5,6]])

In [25]:
A.sum(axis=1)   # 按行求和，方法一

array([ 6, 15])

In [26]:
np.sum(A, axis=1)    # 按行求和，方法二

array([ 6, 15])

In [29]:
A.sum(axis=0)   # 按列求和，方法一

array([5, 7, 9])

In [30]:
np.sum(A, axis=0)    # 按列求和，方法二

array([5, 7, 9])