# value

In [1]:
# 正无穷
import numpy as np
np.inf

inf

In [2]:
import numpy as np
np.sign([-5, 0, 5])

array([-1,  0,  1])

In [5]:
import numpy as np
np.log ([1,2,3,4])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [7]:
import numpy as np
np.exp([0, 1,2,3,4])

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])