In [1]:
import torch

In [3]:
torch.empty(5, 3)

tensor([[9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39],
        [1.0653e-38, 4.1327e-39, 1.0194e-38]])

In [4]:
torch.rand(5, 3)

tensor([[0.5229, 0.0800, 0.9849],
        [0.6595, 0.1467, 0.3670],
        [0.9218, 0.8382, 0.4579],
        [0.0262, 0.8460, 0.5885],
        [0.6535, 0.4521, 0.6572]])

In [5]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [10]:
a = x.new_ones(5, 3, dtype=torch.double)
print (a)
b = torch.randn_like(a, dtype=torch.float)
print (b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1019,  1.3114, -0.5024],
        [-0.4827, -0.0355, -0.8333],
        [ 0.2376, -0.1988,  0.4293],
        [-1.6982, -1.4982, -0.5892],
        [ 1.4525,  0.1414,  1.4661]])


In [11]:
a+b

tensor([[ 2.1019,  2.3114,  0.4976],
        [ 0.5173,  0.9645,  0.1667],
        [ 1.2376,  0.8012,  1.4293],
        [-0.6982, -0.4982,  0.4108],
        [ 2.4525,  1.1414,  2.4661]], dtype=torch.float64)

In [12]:
torch.add(a, b)

tensor([[ 2.1019,  2.3114,  0.4976],
        [ 0.5173,  0.9645,  0.1667],
        [ 1.2376,  0.8012,  1.4293],
        [-0.6982, -0.4982,  0.4108],
        [ 2.4525,  1.1414,  2.4661]], dtype=torch.float64)

In [13]:
result = torch.empty(5, 3)
torch.add(a, b, out=result)
print(result)

tensor([[ 2.1019,  2.3114,  0.4976],
        [ 0.5173,  0.9645,  0.1667],
        [ 1.2376,  0.8012,  1.4293],
        [-0.6982, -0.4982,  0.4108],
        [ 2.4525,  1.1414,  2.4661]])


In [14]:
b.add_(a)

tensor([[ 2.1019,  2.3114,  0.4976],
        [ 0.5173,  0.9645,  0.1667],
        [ 1.2376,  0.8012,  1.4293],
        [-0.6982, -0.4982,  0.4108],
        [ 2.4525,  1.1414,  2.4661]])

In [15]:
a[:,1]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3488])
-0.34880346059799194
