# 文件操作

# 打开文件

In [1]:
filename = "1.txt"
fr = open(filename)   # filename是文件名,fr是文件句柄

# 读文件内容

 ## 1. 一次读入所有的内容，并返回list

In [2]:
filename = "1.txt"
fr = open(filename) 
fr.readlines()  # 一次读入所有的内容，并返回list

['11\t12\t13\t14\ty1\n',
 '21\t22\t23\t24\ty2\n',
 '31\t32\t33\t34\ty3\n',
 '41\t42\t43\t44\ty4']

## 2. readlines只能用一次，再读就读不到了

In [3]:
filename = "1.txt"
fr = open(filename) 
fr.readlines()  
fr.readlines()  # readlines只能用一次，再读就读不到了

[]

In [4]:
fr = open(filename) 
fr.readlines()  # 重新再open一次，就能重新开始读内容了

['11\t12\t13\t14\ty1\n',
 '21\t22\t23\t24\ty2\n',
 '31\t32\t33\t34\ty3\n',
 '41\t42\t43\t44\ty4']

# 处理文件内容

## 1. 依次处理每一行

In [5]:
filename = "1.txt"
fr = open(filename) 
for line in fr.readlines():
    print(line)

11	12	13	14	y1

21	22	23	24	y2

31	32	33	34	y3

41	42	43	44	y4


## 2. 文件中的每一行都以换行符结束，处理时通常要先去掉换行符

In [6]:
filename = "1.txt"
fr = open(filename) 
for line in fr.readlines():   # 依次处理每一行
    line = line.strip()       # 去掉行尾的换行符
    print(line)

11	12	13	14	y1
21	22	23	24	y2
31	32	33	34	y3
41	42	43	44	y4


## 3. 通常一行代表一个样本，一行里面包含一个样本的多个特征，多个特征之间用'\t'格开

In [7]:
filename = "1.txt"
fr = open(filename) 
for line in fr.readlines():   # 依次处理每一行
    line = line.strip()       # 去掉行尾的换行符
    listFromLine = line.split('\t')   # 提取每个特征
    print (listFromLine)

['11', '12', '13', '14', 'y1']
['21', '22', '23', '24', 'y2']
['31', '32', '33', '34', 'y3']
['41', '42', '43', '44', 'y4']


## 4. 如果是监督学习，通常一个样本的前n个数据是特征，最后一个是输出标记

In [8]:
filename = "1.txt"
fr = open(filename) 
for line in fr.readlines():   # 依次处理每一行
    line = line.strip()       # 去掉行尾的换行符
    listFromLine = line.split('\t')   # 提取每个特征
    attr = listFromLine[0:-1]  # 特征向量
    label = listFromLine[-1]  # 输出标记
    print ("特征向量：" + str(attr))
    print ("输出标记：" + label)

特征向量：['11', '12', '13', '14']
输出标记：y1
特征向量：['21', '22', '23', '24']
输出标记：y2
特征向量：['31', '32', '33', '34']
输出标记：y3
特征向量：['41', '42', '43', '44']
输出标记：y4


## 5. 把m个数据n个特征存到m*n的矩阵中，输出标记用list保存

In [13]:
import numpy as np

filename = "1.txt"
fr = open(filename) 
lines = fr.readlines()
numberOfLines = len(lines)

returnMat = np.zeros((numberOfLines, 4))    # 初始化样本特征矩阵
classLabelVector = []                    # 初始化化输出标记列表
index = 0
    
for line in lines:   # 依次处理每一行
    line = line.strip()       # 去掉行尾的换行符
    listFromLine = line.split('\t')   # 提取每个特征
    returnMat[index, :] = listFromLine[0:-1]  # 提取特征向量，并加入到特征矩阵中
    classLabelVector.append(listFromLine[-1])  # 提取输出标记，并加入输出列表中
    
    index += 1
        
print ("样本特征矩阵：" + str(returnMat))
print ("输出标记列表：" + str(classLabelVector))

样本特征矩阵：[[11. 12. 13. 14.]
 [21. 22. 23. 24.]
 [31. 32. 33. 34.]
 [41. 42. 43. 44.]]
输出标记列表：['y1', 'y2', 'y3', 'y4']


# 读文件夹

## 列出某个路径下的所有文件

In [2]:
from os import listdir
listdir("./")

['.ipynb_checkpoints', '1.txt', 'file.ipynb']

# pickle将对象序列化并存储到文件

In [1]:
# pickle将对象序列化成二进制，而不是字符串，所以open参数必须指明'b'
def storeTree(inputTree,filename):
    import pickle
    fw = open(filename,'wb')
    pickle.dump(inputTree,fw)
    fw.close()
def grabTree(filename):
    import pickle
    fr = open(filename, 'rb')
    return pickle.load(fr)

In [3]:
myTree = {'no surfacing': {0: 'no', 1: {'flippers': {0: 'no', 1: 'yes'}}}}
storeTree(myTree,'classifierStorage.txt')
grabTree('classifierStorage.txt')

{'no surfacing': {0: 'no', 1: {'flippers': {0: 'no', 1: 'yes'}}}}