# categorical_corssentropy

$L(y,\tilde y)= - \sum y\log \tilde y$，由于只有$y_i=1$，简化为$L(y, \tilde y) = - \log\tilde y_i$

In [4]:
from tensorflow.keras.losses import categorical_crossentropy
import tensorflow as tf

In [17]:
y_true = tf.constant([1,0],tf.float32)
y_pred = tf.constant([0.5,0.5],tf.float32)
categorical_crossentropy(y_true, y_pred)
# loss = - ln(0.5) = 0.69

<tf.Tensor: shape=(), dtype=float32, numpy=0.6931472>

In [21]:
'''
y_true = 
1 0
1 0
'''
y_true = tf.constant([[1,0],[1,0]],tf.float32)
'''
y_true = 
0.5 0.5
0.3 0.7
'''

y_pred = tf.constant([[0.5,0.5],[0.3,0.7]],tf.float32)
# 分别对每一行计算loss
categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.6931472, 1.2039728], dtype=float32)>

In [23]:
y_true = tf.constant([[[1,0],[1,0]]],tf.float32)
y_pred = tf.constant([[[0.5,0.5],[0.3,0.7]]],tf.float32)
# 高维情况下，都是只对最后一个维度计算loss，其它维度保持不变
categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.6931472, 1.2039728]], dtype=float32)>