In [12]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.1.0'

# 常用的数据处理函数

In [4]:
tf.cast(5, dtype=tf.float32)  # 类型转换

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [5]:
tf.convert_to_tensor([1,2,3,4,5,6])  # 其它类型转为tensor类型

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [18]:
data = tf.reshape([1,2,3,4,5,6], (2,3))    # 维度切换
print (data)
data = tf.reshape([1,2,3,4,5,6], (-1,2))    # 可以使用-1
print (data)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [13]:
data = tf.reshape(np.arange(24), (2,3,4))
print (data.shape)
data = tf.transpose(data, perm=(2,1,0))  # 维度转换
print (data.shape)

(2, 3, 4)
(4, 3, 2)


In [15]:
data = tf.reshape([1,2,3,4,5,6], (2,3))
print (data.shape)
data = data[:, tf.newaxis, tf.newaxis, :]  # 增加维度
print (data.shape)

(2, 3)
(2, 1, 1, 3)


In [17]:
tf.constant([1,2,3,4,5,6])  # 生成常量tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [20]:
data = tf.reshape([1,2,3,4,5,6], (2,3))
tf.shape(data)   # 求数据维度

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [24]:
data = tf.reshape([1,2,3,4,5,6], (2,3))
print (data)
tf.reduce_sum(data)  # 对所有元素求和

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [25]:
tf.equal([1,2,3,4], [1,2,4,5])  # 元素比较

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True, False, False])>

In [27]:
tf.expand_dims([1,2,3,4], 0) # 扩充维度

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]])>

In [7]:
ans = tf.argmax([1,3,5,7,6,4,2])  # 一维数组求最大值的位置
print (ans)
ans = tf.argmax([[1,3,5,7,6,4,2], # 多维数组默认针对第一维求最大值的位置
                 [2,4,6,8,5,3,1]])
print (ans)
ans = tf.argmax([[1,3,5,7,6,4,2], # 多维数组，指定维度求最大值的位置
                 [2,4,6,8,5,3,1]], axis=-1)
print (ans)

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([1 1 1 1 0 0 0], shape=(7,), dtype=int64)
tf.Tensor([3 3], shape=(2,), dtype=int64)


In [11]:
a = [1,2,3]  # 数组拼接
b = [3,2,1]
tf.concat([a, b], axis = -1)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 3, 2, 1])>

# tf.random

In [15]:
tf.random.uniform((3,3,3))   # 第一个参数为数据的形状，默认数据范围为(0,1)，数据分布为？

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.74904656, 0.9453472 , 0.56627226],
        [0.9801376 , 0.69182456, 0.85999334],
        [0.89502037, 0.70597196, 0.0359689 ]],

       [[0.09806931, 0.34866703, 0.26818728],
        [0.8670877 , 0.08579779, 0.36008048],
        [0.20556223, 0.2320118 , 0.02615905]],

       [[0.2040708 , 0.40936053, 0.05890632],
        [0.856591  , 0.15391135, 0.8608304 ],
        [0.73116124, 0.31995678, 0.6113366 ]]], dtype=float32)>

# tf.math

In [18]:
# tf.math.rsqrt(5)
tf.math.minimum(0.001, 0.002)

<tf.Tensor: shape=(), dtype=float32, numpy=0.001>

In [19]:
tf.math.logical_not(True)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [20]:
tf.math.equal(1e-9, 0)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [21]:
tf.math.logical_and(True, False)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

# 版本问题

2.0版本新旧对比：
https://docs.google.com/spreadsheets/d/1FLFJLzg7WNP6JHODX5q8BDgptKafq_slHpnHVbJIteQ/edit#gid=0

In [2]:
tf.enable_eager_execution
# 这句话1.x版本需要，2.x版本不需要

AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

In [2]:
import tensorflow as tf

tf.initialize_all_variables()
# 这句话是1.x的，2.x要换个写法

AttributeError: module 'tensorflow' has no attribute 'initialize_all_variables'

In [3]:
tf.compat.v1.global_variables_initializer()

In [4]:
tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [5]:
tf.compat.v1.Session()

# The Session graph is empty.

In [6]:
init = tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as session: 
    session.run(init)                            # Initializes the variables

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [11]:
tf.compat.v1.disable_eager_execution() # 保证sess.run()能够正常运行
init = tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as session: 
    session.run(init)  

# Can not convert a ResourceVariable into a Tensor or Operation

In [20]:
y_hat = tf.constant(36, name='y_hat')            # Define y_hat constant. Set to 36.
y = tf.constant(39, name='y')                    # Define y. Set to 39

loss = tf.Variable((y - y_hat)**2, name='loss')  # Create a variable for the loss
tf.compat.v1.disable_eager_execution()
init = tf.compat.v1.global_variables_initializer()
# init = tf.global_variables_initializer()         # When init is run later (session.run(init)),
                                                 # the loss variable will be initialized and ready to be computed
with tf.compat.v1.Session() as session: 
# with tf.Session() as session:                    # Create a session and print the output
    session.run(init)                            # Initializes the variables
    print(session.run(loss))                     # Prints the loss
# 原因：接收的参数名和run（）里面的参数名一样了，这样的话，第一次不会报错，下一次运行中，test_fc1，test_fc2变量名已有了，直接跑会和你前面定义的test_fc1，test_fc2相关运算冲突。 所以将接收的变量名改了就可以了。

9


# module 'tensorflow_core._api.v2.train' has no attribute 'AdamOptimizer'

In [22]:
model.compile(optimizer = tf.train.AdamOptimizer(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

NameError: name 'model' is not defined

In [ ]:
model.compile(optimizer = tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])