# 一个矩阵和一个向量之间的操作

In [1]:
import numpy as np   # 调用numpy函数时显示地使用"np."来调用，以区分这个函数是否属于numpy

# 矩阵（二维数组）与向量（一维数组）的加减

In [2]:
A = np.array([[1,1,1],[2,2,2]])
b = [1,2,3]

# A的列数必须 = b的列数
# ret_i_j = A_i_j 加减乘除 b_j

In [3]:
A + b

array([[2, 3, 4],
       [3, 4, 5]])

In [4]:
A - b

array([[ 0, -1, -2],
       [ 1,  0, -1]])

In [5]:
A * b

array([[1, 2, 3],
       [2, 4, 6]])

In [6]:
A / b

array([[1.        , 0.5       , 0.33333333],
       [2.        , 1.        , 0.66666667]])