In [2]:
import numpy as np

In [3]:
complex(1, 2)

(1+2j)

In [4]:
complex(1, 2) * complex(3, 4)

(-5+10j)

In [5]:
np.abs(complex(1, 2))

2.23606797749979

In [6]:
np.array([complex(1, 2), complex(3, 4)])

array([1.+2.j, 3.+4.j])

In [7]:
np.abs(np.array([complex(1, 2), complex(3, 4)]))

array([2.23606798, 5.        ])

In [10]:
np.array([complex(1, 2), complex(3, 4)]).shape

(2,)

In [11]:
A = np.array([
    [complex(1, 1), complex(2, 2)],
    [complex(3, 3), complex(4, 4)]
])
print (A)

[[1.+1.j 2.+2.j]
 [3.+3.j 4.+4.j]]


In [13]:
b = np.array([
    complex(1, 1), complex(2, 2)
])
print (b)

[1.+1.j 2.+2.j]


In [14]:
A.dot(b)

array([0.+10.j, 0.+22.j])

In [1]:
a = complex(1, 2)
a.real

1.0

In [2]:
a.imag

2.0