In [4]:
import numpy as np

# 创建全0向量/矩阵

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 创建全1向量/矩阵

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 创建空的向量/矩阵

为什么结果和ones是一样的？我也不知道

In [13]:
np.empty(3)

array([1., 1., 1.])

In [14]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 创建指定值的向量/矩阵

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [21]:
np.linspace(1,10,6).reshape((2,3))

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

# 创建指定类型的向量/矩阵

默认类型是int64，如果已经值的范围，调整类型可以节省空间

In [22]:
np.array([1,2,3], dtype='int32')

array([1, 2, 3])