# 针对一个矩阵的操作

In [1]:
import numpy as np   # 调用numpy函数时显示地使用"np."来调用，以区分这个函数是否属于numpy

# 创建向量

In [3]:
# 创建一维数组
np.array([1,2,3])

array([1, 2, 3])

In [2]:
# 创建全0的矩阵
np.zeros(5)   # 注意这里有两层小括号

array([0., 0., 0., 0., 0.])

In [3]:
# 由一个字符串来创建矩阵
import numpy as np
a = "12345"
A = np.array(list(a),dtype='int')
A

array([1, 2, 3, 4, 5])

In [4]:
# 创建一个空的一维数组
np.zeros(0)

array([], dtype=float64)

# 获取向量的元素个数

In [5]:
a = np.array([1,2,3])
a.shape[0]

3

In [6]:
a = np.array([1,2,3])
len(a)

3

# 取向量中的非零元素的索引

In [7]:
# list
import numpy as np
a = [1,0,2,0,3]
np.nonzero(a)

(array([0, 2, 4], dtype=int64),)

In [8]:
# 一维向量
import numpy as np
a = np.array([1,0,2,0,3])
np.nonzero(a)

(array([0, 2, 4], dtype=int64),)

# 矩阵的扩展

In [10]:
a = np.array([1,0,2,0,3])
a[:, np.newaxis]

array([[1],
       [0],
       [2],
       [0],
       [3]])

In [11]:
a[np.newaxis, :]

array([[1, 0, 2, 0, 3]])

# 对数组的排序并返回结果索引

In [14]:
a = np.array([1,3,5,7,2,4,6,8])
a.argsort()  # 默认从小到大

array([0, 4, 1, 5, 2, 6, 3, 7], dtype=int64)

# 计算方差

In [4]:
# 向量的方差
import numpy as np
a = np.array([1,2,3])
b = np.array([1,1,1])
print(a.var(),b.var())

0.6666666666666666 0.0


# 计算平均值

In [12]:
# 一维数组的平均值
import numpy as np
a = np.array([1,2,3])
print(a.mean())
print (a.mean(axis=0)) # 两种写法

2.0
2.0


In [13]:
import numpy as np
A = np.array([4,5,1,2,3])
A.argmin()

2

# 求中位数

In [14]:
import numpy as np
A = np.array([1,2,3,4, 10])
np.median(A)   # 奇数个数字的情况下得到的是中位数

3.0

In [15]:
import numpy as np
A = np.array([1,2,3,4, 10,11])
np.median(A)   # 偶数个数字的情况下得到的是两个中位数的平均值

3.5

In [16]:
A = np.array([1,2,3,4, 10,11])
np.median?